# authendication credintials
credentials:
  usernames:
    meher:
      email: meher@gmail.com
      name: Tasnima Meheraj
      password: vzkOZV0TTsTWpysfZHhI3m # Placeholder for hashed password of 'abc'

cookie:
  expiry_days: 1
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - meherkh@growwithdata.net



db:
  host: "localhost"
  user: "root"
  passwd: "A@@ZtLS31rBMk"
  database: "ExpenseDB"
  auth_plugin: "mysql_native_password"

  
email_sender:
  email: "meher.resource@gmail.com"
  pass: 'Rob@@9H
'